export { default as Login } from "./login";
export { default as Cadastro } from "./cadastro";
export { default as Home } from "./home";
export { default as Historico } from "./historico";
export { default as Profile } from "./profile";
export { default as Reservar } from "./reservar";
export { default as ReservaRealizada } from "./reservaRealizada";
export { default as ReservaCancelada } from "./reservaCancelada";
export { default as DetalhesReserva } from "./detalhesReserva";
